config/routes.rb
Rails.application.routes.draw do


  # 顧客用
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  root to: "public/homes#top"
  get '/about' => 'public/homes#about'


  namespace :admin do

    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show]
  end


  namespace :public do

    get "/users/quit" => "users#quit"
    patch "/users/out" => "users#out"


    resources :users, only: [:show, :edit, :update, :create]
    resources :posts, only: [:index, :new, :show, :edit, :destroy, :create, :update]do
      collection do
        get 'search'
      end
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :drives, only: [:new, :index, :edit, :update, :destroy, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  attachment :image
  attachment :profile_image

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :image, presence: true




  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end


end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.page(params[:page]).per(6).reverse_order
  end

  def show
    @post = Post.find(params[:id])
    
  end


  private
   def post_params
     params.require(:post).permit(:image, :title, :body, :profile_image, :keyword)
   end


end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="container">
 <h1>ユーザー投稿一覧</h1>
  <div class="row row-cols-1 row-cols-sm-4">
   <% @posts.each do |post| %>
   <div class="col-md-auto">
    <div class="card h-100">
     <div class="img-fuid" alt="card-grid-image">
      <%= attachment_image_tag post, :image, format: 'jpeg', size: '300' %>
     </div>
     <div class="card-body m-auto">
      <h5 class="card-title">
       <p>お出かけ先</p>
       <%= link_to post.title, admin_post_path(post.id)  %>
      </h5>
      <p class="card-text">
       投稿者
       <%= link_to post.user.name, admin_user_path(post.user_id) %>
      </p>
      <p class="card-text"><small class="text-muted"><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></small></p>
     </div>
    </div>

   </div>
    <% end %>
  </div>
</div>
<%= paginate @posts %>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
   <div class="col-md-auto">
    <h1>ユーザー投稿詳細</h1>
    <div class="p-1 border bg-light">
     <div class="card h-100">
      <div class="card-img-top" alt="card-img-top"><%= attachment_image_tag @post, :image, format: 'jpeg', size: "auto" %></div>
       <div class="card-body">
        <h4 class="card-title"><%= @post.title %></h4>
        <p class="card-text"><%=safe_join(@post.body.split("\n"),tag(:br)) %></p>
        <p class="card-text">ユーザーネーム:<%= link_to @post.user.name, admin_user_path(@post.user_id) %></p>
        <p class="card-text"><small class="text-muted"><%= @post.created_at.strftime("%Y-%m-%d %H:%M") %></small></p>
       </div>
      </div>
     </div>
    </div>
  </div>
</div>