config/routes.rb
Rails.application.routes.draw do


  # 顧客用
devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


  root to: "public/homes#top"
  get '/about' => 'public/homes#about'


  namespace :admin do

    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show]
  end


  namespace :public do

    get "/users/quit" => "users#quit"
    patch "/users/out" => "users#out"


    resources :users, only: [:show, :edit, :update, :create]
    resources :posts, only: [:index, :new, :show, :edit, :destroy, :create, :update]do
      collection do
        get 'search'
      end
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :drives, only: [:new, :index, :edit, :update, :destroy, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :posts, dependent: :destroy
  has_many :drives, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image


  validates :name,uniqueness: true, length: { minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 150}
 


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController



  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(3).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
   @user = User.find(params[:id])
   @user.update(user_params)
   redirect_to admin_user_path(@user.id)
  end

  private

  def user_params
   params.require(:user).permit(:email, :name, :profile_image, :introduction, :is_deleted)
  end


end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<h>ユーザー情報編集</h>

<h4>会員ID</h4>
<%= @user.id %>

<%= form_with model: @user, url: admin_user_path(@user.id),  local:true do |f| %>
<h4>ユーザーネーム</h4>
<%= f.text_field :name %>
<h4>メールアドレス</h4>
<%= f.email_field :email %>
<h4>会員ステータス</h4>
<%= f.radio_button :is_deleted, :true %>退会
<%= f.radio_button :is_deleted, :false %>有効

<%= f.submit "編集内容を保存" %>
<% end %>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
   <div class="col-md-auto">
    <h1>ユーザー一覧</h1>
    <table class="table table-hover">
     <thead>
      <tr>
       <th scope="col">会員ID</th>
       <th scope="col">ユーザーネーム</th>
       <th scope="col">メールアドレス</th>
       <th scope="col">会員ステータス</th>
      </tr>
     </thead>
     <% @users.each do |user| %>
      <tbody>
       <tr>
        <td><%= user.id %></td>
        <td>
         <%= link_to admin_user_path(user.id) do %>
          <%= user.name %>
         <% end %>
         </td>
        <td><%= user.email %></td>
        <td>
         <% if user.is_deleted == true %>
          退会
         <% else %>
          有効
         <% end %>
        </td>
       </tr>
      </tbody>
     <% end %>
    </table>
  </div>
 </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
   <div class="col-md-3">
    <h1>会員詳細</h1>
    <div class="p-1 border bg-light">
     <div class="card h-100">
      <div class="text-center">
       <div class="card-img-top"  alt="card-img-top"><%= attachment_image_tag @user, :profile_image, size: '100', fallback: "no_image.jpg", class: "rounded-circle" %></div>
      </div>
      <div class="card-body">
       <p class="card-title">
        会員ID:
        <%= @user.id %><br>
        ユーザーネーム:
        <%= @user.name %><br>
        メールアドレス:
        <%= @user.email %><br>
        会員ステータス:
         <% if @user.is_deleted == true %>
          退会
         <% else %>
          有効
         <% end %>
       </p>
       <p class="card-text">
        <%= link_to "編集する", edit_admin_user_path %>
       </p>
      </div>
     </div>
    </div>
   </div>
   <div class="col-md-auto">
    <h1>ユーザー投稿一覧</h1>
    <div class="row">
     <% @posts.each do |post| %>
      <div class="col-md-auto">
       <div class="p-1 border bg-light">
        <div class="card">
         <div class="img-fluid" alt="card-grid-image">
          <%= attachment_image_tag post, :image, format: 'jpeg', size: '200' %>
         </div>
         <div class="card-body m-auto">
          <h5 class="card-title">
           お出かけ先<br>
           <%= link_to post.title, admin_post_path(post.id)  %>
          </h5>
          <p class="card-text">
           投稿者<br>
           <%= link_to post.user.name, admin_user_path(post.user_id) %>
          </p>
          <p class="card-text"><small class="text-muted"><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></small></p>
         </div>
        </div>
       </div>
      </div>
      <% end %>
    </div>
    <%= paginate @posts %>
   </div>
  </div>
</div>